1.out: activity1.cpp
	g++ activity1.cpp -o 1.out

2.out: activity2.cpp
	g++ activity2.cpp -o 2.out

3.out: activity3.cpp
	g++ activity3.cpp -o 3.out

4.out: activity4.cpp
	g++ activity4.cpp -o 4.out

5.out: activity5.cpp
	g++ activity5.cpp -o 5.out

6.out: activity6.cpp
	g++ activity6.cpp -o 6.out

7.out: activity7.cpp
	g++ activity7.cpp -o 7.out

8.out: activity8.cpp
	g++ activity8.cpp -o 8.out

clean:
	rm -rf *.out


all: 1.out 2.out 3.out 4.out 5.out 6.out 7.out 8.out